chore: make clippy happy
No changes in the file and I get this error
Error:   --> server/src/uuid/model/entity_revision/abstract_entity_revision.rs:26:54
   |
26 | #[derive(Copy, Clone, Debug, Deserialize, Serialize, PartialEq)]
   |                                                      ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`